#!/bin/bash

ATTFILE=/root/sohn
ATTNAME=test.pdf
MAILTO=homaar@tobias-weiss.org
MAILFROM=spam@tobias-weiss.org

uuencode $ATTFILE $ATTNAME | sendmail -v -f ${MAILFROM} ${MAILTO}

#for i in {1..3}
#do
	#echo "Hosch sowas schommal gesehn?" | mutt -s "BÄM!" homaar@tobias-weiss.org
	#echo "Hosch sowas schommal gesehn?" | mutt -s "RAID WARNING! DANGER!" nomed@kabelbw.de -a /100MB.qsc
#done

